services:
  - type: web
    name: fastapi-mental-health-api
    runtime: python
    repo: https://github.com/ahmedusama14/railway
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 5000
    envVars:
      - key: PORT
        value: 5000
    plan: free
